
package codigo;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author @writters @directors
 * Mohamed El Boudakhani Ikatouaran
 * Miren Ordóñez de Arce
 */
public class PanelColores extends javax.swing.JPanel {
    
    public Color colorSeleccionado = Color.BLACK;
    
    /**
     * Creates new form PanelColores
     */
    public PanelColores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        negro = new javax.swing.JLabel();
        naranja = new javax.swing.JLabel();
        amarillo = new javax.swing.JLabel();
        gris = new javax.swing.JLabel();
        morado = new javax.swing.JLabel();
        rojo = new javax.swing.JLabel();
        blanco = new javax.swing.JLabel();
        azulClaro = new javax.swing.JLabel();
        azulOscuro = new javax.swing.JLabel();
        rosa = new javax.swing.JLabel();
        verdeClaro = new javax.swing.JLabel();
        verdeOscuro = new javax.swing.JLabel();
        colorElegido = new javax.swing.JLabel();

        negro.setBackground(new java.awt.Color(0, 0, 0));
        negro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, null));
        negro.setOpaque(true);
        negro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                negroMousePressed(evt);
            }
        });

        naranja.setBackground(new java.awt.Color(255, 153, 0));
        naranja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        naranja.setOpaque(true);
        naranja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                naranjaMousePressed(evt);
            }
        });

        amarillo.setBackground(new java.awt.Color(255, 255, 0));
        amarillo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        amarillo.setOpaque(true);
        amarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                amarilloMousePressed(evt);
            }
        });

        gris.setBackground(new java.awt.Color(102, 102, 102));
        gris.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gris.setOpaque(true);
        gris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                grisMousePressed(evt);
            }
        });

        morado.setBackground(new java.awt.Color(153, 0, 153));
        morado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        morado.setOpaque(true);
        morado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moradoMousePressed(evt);
            }
        });

        rojo.setBackground(new java.awt.Color(255, 0, 0));
        rojo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rojo.setOpaque(true);
        rojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rojoMousePressed(evt);
            }
        });

        blanco.setBackground(new java.awt.Color(255, 255, 255));
        blanco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        blanco.setOpaque(true);
        blanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                blancoMousePressed(evt);
            }
        });

        azulClaro.setBackground(new java.awt.Color(102, 255, 255));
        azulClaro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        azulClaro.setOpaque(true);
        azulClaro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                azulClaroMousePressed(evt);
            }
        });

        azulOscuro.setBackground(new java.awt.Color(0, 0, 255));
        azulOscuro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        azulOscuro.setOpaque(true);
        azulOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                azulOscuroMousePressed(evt);
            }
        });

        rosa.setBackground(new java.awt.Color(255, 0, 255));
        rosa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rosa.setOpaque(true);
        rosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rosaMousePressed(evt);
            }
        });

        verdeClaro.setBackground(new java.awt.Color(51, 255, 102));
        verdeClaro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verdeClaro.setOpaque(true);
        verdeClaro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verdeClaroMousePressed(evt);
            }
        });

        verdeOscuro.setBackground(new java.awt.Color(0, 102, 51));
        verdeOscuro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verdeOscuro.setOpaque(true);
        verdeOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verdeOscuroMousePressed(evt);
            }
        });

        colorElegido.setBackground(new java.awt.Color(0, 0, 0));
        colorElegido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        colorElegido.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(colorElegido, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(negro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gris, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(rosa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(azulClaro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(blanco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(naranja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(morado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(azulOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verdeClaro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verdeOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(colorElegido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gris, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(negro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rosa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(azulClaro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(verdeClaro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(naranja, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blanco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(morado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(azulOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verdeOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void naranjaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naranjaMousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground(); 
        colorElegido.setBackground(colorSeleccionado);
    }//GEN-LAST:event_naranjaMousePressed

    private void negroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_negroMousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorElegido.setBackground(colorSeleccionado);
    }//GEN-LAST:event_negroMousePressed

    private void blancoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blancoMousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorElegido.setBackground(colorSeleccionado);
    }//GEN-LAST:event_blancoMousePressed

    private void grisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grisMousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorElegido.setBackground(colorSeleccionado);
    }//GEN-LAST:event_grisMousePressed

    private void amarilloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amarilloMousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorElegido.setBackground(colorSeleccionado);
    }//GEN-LAST:event_amarilloMousePressed

    private void rosaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rosaMousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorElegido.setBackground(colorSeleccionado);
    }//GEN-LAST:event_rosaMousePressed

    private void moradoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moradoMousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorElegido.setBackground(colorSeleccionado);
    }//GEN-LAST:event_moradoMousePressed

    private void azulClaroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_azulClaroMousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorElegido.setBackground(colorSeleccionado);
    }//GEN-LAST:event_azulClaroMousePressed

    private void azulOscuroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_azulOscuroMousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorElegido.setBackground(colorSeleccionado);
    }//GEN-LAST:event_azulOscuroMousePressed

    private void verdeClaroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeClaroMousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorElegido.setBackground(colorSeleccionado);
    }//GEN-LAST:event_verdeClaroMousePressed

    private void verdeOscuroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeOscuroMousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorElegido.setBackground(colorSeleccionado);
    }//GEN-LAST:event_verdeOscuroMousePressed

    private void rojoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rojoMousePressed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        colorElegido.setBackground(colorSeleccionado);
    }//GEN-LAST:event_rojoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amarillo;
    private javax.swing.JLabel azulClaro;
    private javax.swing.JLabel azulOscuro;
    private javax.swing.JLabel blanco;
    private javax.swing.JLabel colorElegido;
    private javax.swing.JLabel gris;
    private javax.swing.JLabel morado;
    private javax.swing.JLabel naranja;
    private javax.swing.JLabel negro;
    private javax.swing.JLabel rojo;
    private javax.swing.JLabel rosa;
    private javax.swing.JLabel verdeClaro;
    private javax.swing.JLabel verdeOscuro;
    // End of variables declaration//GEN-END:variables
}
